
sudo: required
services:
  - docker

script:
  - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server


deploy:
  provider: elasticbeanstalk  # set of containers hosting delegate to Amazon Elastic Container Service(ECS) with task defintions
  region: us-east-2
  app: docker-scraping
  env: DockerScraping-env  
  bucket_name: elasticbeanstalk-us-east-2-601631817381  
  bucket_path: scrapings
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  # secret_access_key:
  #   secure: $AWS_SECRET_KEY
