
sudo: required
services:
  - docker

script:
  - docker build -t enginepdf/multi-client ./client   # multi- for image name, ./client is build context using by default Dockerfile to build
  - docker build -t enginepdf/multi-nginx ./nginx
  - docker build -t enginepdf/multi-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push enginepdf/multi-client
  - docker push enginepdf/multi-nginx
  - docker push enginepdf/multi-server


deploy:
  provider: elasticbeanstalk  # set of containers hosting delegate to Amazon Elastic Container Service(ECS) with task defintions
  region: us-east-2
  app: scraping
  env: Scraping-env  
  bucket_name: elasticbeanstalk-us-east-2-601631817381  
  bucket_path: scrapings
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  # secret_access_key:
  #   secure: $AWS_SECRET_KEY
