version: '3'
services:
  mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: balaan
      MYSQL_USER: user 
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    expose:
      - "3306"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3060:80' # local to inside of container
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # just use the directory
      - ./server:/app # copy to app in container
    environment:
      SECRET_KEY: jwt
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: mysql
      DATABASE_USER: user
    depends_on:
      - mysql
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true


      # docker-compose up
      #  docker-compose up --build